[project]
name = "auto-issue-labeler-test"
version = "0.1.0"
description = "Pixi-managed Python environment for this repo"
channels = ["conda-forge"]
platforms = ["linux-64"]

# Default dependencies (shared by all environments unless opted out)
[dependencies]
# pass

# Dataset feature - for dataset creation tasks
[feature.dataset.dependencies]
python = "3.13.*"
openai = "*"
awkward = "*"
requests = "*"
pyyaml = "*"

[feature.dataset.pypi-dependencies]
datasets = "*"
huggingface-hub = "*"

[feature.dataset.tasks]
# Run arbitrary python scripts inside the pixi environment:
# usage:
#   pixi run py scripts/label_issue.py --arg ...
py = "python"
# Convenience tasks for existing scripts
fetch-issues = "bash scripts/fetch_github_issues.sh"
label-issue = "python scripts/label_issue.py"
create-dataset = "python scripts/create_dataset.py"

# Fine-tuning feature - for model training
[feature.finetune.dependencies]
python = "3.12.*"  # Override the default Python version
gxx_linux-64 = "*"
sysroot_linux-64 = "==2.34"
kernel-headers_linux-64 = "==5.14.0"

pip = "*"

[feature.finetune.pypi-dependencies]
jupyterlab = "*"
trl = "==0.21.0"
accelerate = "==1.10.0"
peft = "==0.17.0"
triton = "==3.4.0"
tqdm = "*"
ipywidgets = "*"
iprogress = "*"
jupyter = "*"
transformers = "==4.55.2"
safetensors = "==0.6.2"
sentencepiece = "==0.2.1"
protobuf = "==5.29.5"
datasets = "==3.6.0"
huggingface_hub = "==0.34.4"
hf_transfer = "==0.1.9"
unsloth-zoo = "==2025.8.8"
unsloth = "==2025.8.9"
cut-cross-entropy = "==25.1.1"
xformers = "==0.0.32.post2"
bitsandbytes = "==0.47.0"

[feature.finetune.tasks]
nb = "jupyter lab"
py = "python"

# Define environments
[environments]
ds = ["dataset"]
ft = {features = ["finetune"]}