name: Issue Labeler

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    env:
      # Default knobs for Phase 1 (can be overridden at workflow_dispatch or env)
      LABELER_DRY_RUN: "false"
      OPENAI_MODEL: "gpt-4o-mini"
      OPENAI_TIMEOUT_SECS: "20"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Label issue (LLM-assisted)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LABELER_DRY_RUN: ${{ env.LABELER_DRY_RUN }}
          OPENAI_MODEL: ${{ env.OPENAI_MODEL }}
          OPENAI_TIMEOUT_SECS: ${{ env.OPENAI_TIMEOUT_SECS }}
        run: |
          python scripts/label_issue.py